# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (c) 2025 - present Incudo Labs Inc.
#
# This file is part of Orion's Belt Project (https://github.com/IncudoLABS/orions-belt).
#
# Published by the IncudoLABS.
# Original author: Marko Sarunac <128757181+SaruWiz@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Playbook ID: OB-CFG-002
---
- name: Remove Wazuh Agent from Linux
  hosts: "{{ target_hosts }}"
  gather_facts: no
  become: yes
  vars:
    wazuh_install_dir: /var/ossec

  tasks:
    - name: Stop and disable Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: stopped
        enabled: no
      ignore_errors: yes
      delegate_to: "{{ ansible_delegate_to | default(omit) }}"

    - name: Remove Wazuh agent package (Debian/Ubuntu)
      ansible.builtin.apt:
        name: wazuh-agent
        state: absent
        purge: yes
      when: ansible_pkg_mgr == "apt"
      register: apt_remove_result
      delegate_to: "{{ ansible_delegate_to | default(omit) }}"

    - name: Remove Wazuh agent package (RedHat/CentOS/Fedora)
      ansible.builtin.yum:
        name: wazuh-agent
        state: absent
      when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"
      register: yum_remove_result
      delegate_to: "{{ ansible_delegate_to | default(omit) }}"

    - name: Remove Wazuh agent package (SLES/openSUSE)
      community.general.zypper:
        name: wazuh-agent
        state: absent
      when: ansible_pkg_mgr == "zypper"
      register: zypper_remove_result
      delegate_to: "{{ ansible_delegate_to | default(omit) }}"

    - name: Ensure Wazuh agent installation directory is removed (purge)
      ansible.builtin.file:
        path: "{{ wazuh_install_dir }}"
        state: absent
      register: dir_remove_result
      delegate_to: "{{ ansible_delegate_to | default(omit) }}"

    - name: Display completion message
      debug:
        msg: "Wazuh agent removal completed and configuration purged."
      when: >
        apt_remove_result.changed | default(false) or
        yum_remove_result.changed | default(false) or
        zypper_remove_result.changed | default(false) or
        dir_remove_result.changed | default(false)
      delegate_to: "{{ ansible_delegate_to | default(omit) }}"

    - name: Display message if agent was not found or already removed
      debug:
        msg: "Wazuh agent was not found or already removed."
      when: not (
        apt_remove_result.changed | default(false) or
        yum_remove_result.changed | default(false) or
        zypper_remove_result.changed | default(false) or
        dir_remove_result.changed | default(false)
        )
      delegate_to: "{{ ansible_delegate_to | default(omit) }}" 