# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (c) 2025 - present Incudo Labs Inc.
#
# This file is part of Orion's Belt Project (https://github.com/IncudoLABS/orions-belt).
#
# Published by the IncudoLABS.
# Original author: Marko Sarunac <128757181+SaruWiz@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Script ID: OB-014

- name: Define minimal allowed services
  set_fact:
    minimal_allowed_services:
      - ssh
      - dns
      - ntp

- name: Define minimal allowed ports
  set_fact:
    minimal_allowed_ports:
      - 22    # SSH
      - 53    # DNS
      - 123   # NTP

- name: Display minimal configuration
  debug:
    msg: |
      === MINIMAL FIREWALL CONFIGURATION ===
      Minimal services to allow: {{ minimal_allowed_services | join(', ') }}
      Minimal ports to allow: {{ minimal_allowed_ports | join(', ') }}
      
      This configuration provides maximum security by only allowing:
      - SSH (port 22) - Always allowed from local subnet
      - DNS (port 53) - For name resolution
      - NTP (port 123) - For time synchronization
      
      WARNING: This will block all other services including web servers,
      databases, and other applications. Only use this if you're sure
      no other services are needed.

- name: Prompt for confirmation of minimal configuration
  pause:
    prompt: |
      === MINIMAL FIREWALL CONFIRMATION ===
      
      WARNING: This configuration will block ALL services except:
      - SSH (port 22) - From local subnet only
      - DNS (port 53) - For name resolution
      - NTP (port 123) - For time synchronization
      
      This will likely break web servers, databases, and other applications.
      
      Are you sure you want to proceed with minimal configuration? (y/n):
  register: minimal_confirmation

- name: Configure firewall with minimal settings
  include_tasks: configure_firewall_tasks.yml
  vars:
    allowed_services: "{{ minimal_allowed_services }}"
    allowed_ports: "{{ minimal_allowed_ports }}"
  when: minimal_confirmation.user_input | lower == 'y' 