# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (c) 2023 - present Expiscor Group Inc.
#
# This file is part of Orion's Belt Project (https://github.com/IncudoLABS/orions-belt).
#
# Published by the IncudoLABS.
# Original author: Marko Sarunac <128757181+SaruWiz@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Production Environment Configuration Overrides
# This file contains production-specific values that override config.yml

# Network Configuration Overrides
network:
  # Production-specific subnet
  default_local_subnet: "10.1.0.0/24"
  
  # SSH configuration overrides
  ssh:
    port: 22
    protocol: 2
    allow_root_login: false
    allow_root_login_with_cert: true  # Allow root login with certificate authentication
    password_authentication: false
    key_authentication: true
    empty_passwords: false
    ignore_rhosts: true
    hostbased_authentication: false
    permit_empty_passwords: false
    x11_forwarding: false
    max_auth_tries: 3
    client_alive_interval: 300
    client_alive_count_max: 2
    login_grace_time: 60
    allow_users: []
    deny_users: []
    allow_groups: []
    deny_groups: []

# Authentication Configuration Overrides
authentication:
  # PAM security settings
  pam:
    password_minlen: 12
    password_complexity: "yes"
    password_history: 5
    account_lockout: "yes"
    account_lockout_attempts: 3
    account_lockout_time: 900
    account_lockout_reset_time: 1800
    session_timeout: 3600
    remember_count: 5
  
  # Password policy settings
  password_policies:
    minlen: 12
    maxlen: 128
    minclass: 4
    maxrepeat: 3
    maxsequence: 3
    maxclassrepeat: 4
    gecoscheck: "yes"
    dictcheck: "yes"
    usercheck: "yes"
    enforcing: "yes"
    retry: 3
    difok: 5
    ucredit: -1
    lcredit: -1
    dcredit: -1
    ocredit: -1
    minage: 1
    maxage: 90
    warnage: 7
    inactive: 30
    expire: "yes"
  
# Security Hardening Production Overrides
security_hardening:
  aide:
    # Production-specific AIDE settings
    alert_email: "security@yourdomain.com"
    check_interval_hours: 12  # More frequent checks in production
  
  firewall:
    # Production firewall settings
    default_policy: "drop"
    allow_icmp: false  # Stricter in production
    rate_limit_ssh: true
    ssh_rate_limit: "3/minute"  # Stricter rate limiting

# Wazuh Production Configuration
wazuh:
  agent:
    manager_host: "10.1.0.0"  # Production Wazuh manager
    default_group: "servers"
    registration_timeout: 300
    check_interval: 30  # More frequent checks in production

# Active Directory Configuration
active_directory:
  domain: "yourdomain.com"
  computer_ou: "OU=Computers"
  admin_user: "Administrator"
  # Password should be stored in vault or environment variable
  # admin_password: "{{ vault_ad_password }}"

# Package Management Production Settings
package_management:
  auto_update: false  # Manual updates in production
  security_updates_only: true
  update_schedule: "weekly"
  
  # Production-specific packages
  essential_packages:
    - curl
    - vim
    - sudo
    - fail2ban
    - nftables
    - htop
    - iotop
    - netstat-nat

# Logging Production Configuration
logging:
  # Production logging settings
  log_retention_days: 365  # Longer retention in production
  log_rotation: "daily"
  
  audit:
    enabled: true
    log_file: "/var/log/audit/audit.log"
    max_log_file_mb: 200  # Larger log files in production
    num_logs: 10

# Monitoring Production Settings
monitoring:
  system_metrics: true
  disk_usage_threshold: 80  # Lower threshold in production
  memory_usage_threshold: 85
  cpu_usage_threshold: 75
  
  # Production alerting
  email_alerts: true
  email_recipients:
    - "security@yourdomain.com"

# Backup Production Configuration
backup:
  enabled: true
  backup_directory: "/var/backups/production"
  retention_days: 90
  compression: true
  encryption: true  # Encrypted backups in production

# Development/Testing Configuration
development:
  # Test mode settings
  test_mode: false
  dry_run: false
  verbose_output: false
  
  # Debug settings
  debug_level: "info"
  log_ansible_tasks: false