# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (c) 2023 - present Expiscor Group Inc.
#
# This file is part of Orion's Belt Project (https://github.com/IncudoLABS/orions-belt).
#
# Published by the IncudoLABS.
# Original author: Marko Sarunac <128757181+SaruWiz@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Orion's Belt Ansible Configuration
# This file contains all externalized configuration variables for the project

# Network Configuration
network:
  # Default local subnet for firewall rules
  default_local_subnet: ""
  
  # SSH configuration
  ssh:
    port: 22
    protocol: 2
    allow_root_login: false
    allow_root_login_with_cert: true  # Allow root login with certificate authentication
    password_authentication: false
    key_authentication: true
    empty_passwords: false
    ignore_rhosts: true
    hostbased_authentication: false
    permit_empty_passwords: false
    x11_forwarding: false
    max_auth_tries: 3
    client_alive_interval: 300
    client_alive_count_max: 2
    login_grace_time: 60
    allow_users: []
    deny_users: []
    allow_groups: []
    deny_groups: []

# Authentication Configuration
authentication:
  # PAM security settings
  pam:
    password_minlen: 12
    password_complexity: "yes"
    password_history: 5
    account_lockout: "yes"
    account_lockout_attempts: 3
    account_lockout_time: 900
    account_lockout_reset_time: 1800
    session_timeout: 3600
    remember_count: 5
  
  # Password policy settings
  password_policies:
    minlen: 12
    maxlen: 128
    minclass: 4
    maxrepeat: 3
    maxsequence: 3
    maxclassrepeat: 4
    gecoscheck: "yes"
    dictcheck: "yes"
    usercheck: "yes"
    enforcing: "yes"
    retry: 3
    difok: 5
    ucredit: -1
    lcredit: -1
    dcredit: -1
    ocredit: -1
    minage: 1
    maxage: 90
    warnage: 7
    inactive: 30
    expire: "yes"

# Security Hardening Configuration
security_hardening:
  # AIDE (Advanced Intrusion Detection Environment) Configuration
  aide:
    database_path: "/var/lib/aide/aide.db"
    config_file: "/etc/aide/aide.conf"
    log_directory: "/var/log/aide"
    check_interval_hours: 24
    alert_email: "root@localhost"
  
  # Firewall Configuration
  firewall:
    default_policy: "drop"
    allow_icmp: true
    rate_limit_ssh: true
    ssh_rate_limit: "5/minute"

# Wazuh Security Platform Configuration
wazuh:
  agent:
    manager_host: "X.X.X.X"
    # Password should be stored in vault or environment variable
    # manager_password: "{{ vault_wazuh_password }}"
    default_group: "servers"
    registration_timeout: 300
    check_interval: 60
    # The version of the Wazuh agent to be deployed.
    version: "4.12.0-1"

  # Wazuh agent groups by environment
  groups:
    production:
      - "production-servers"
      - "web-servers"
      - "database-servers"
    staging:
      - "staging-servers"
      - "test-servers"
    development:
      - "dev-servers"
      - "lab-servers"

# Kernel Security Configuration
kernel_modules:
  disable_list:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - usb-storage
    - dccp
    - sctp
    - rds
    - tipc

# Active Directory Configuration
active_directory:
  domain: "domain.com"
  computer_ou: "OU=Computers"
  admin_user: "Administrator"
  # Password should be stored in vault or environment variable
  # admin_password: "{{ vault_ad_password }}"


# Package Management Configuration
package_management:
  # Update policies
  auto_update: false
  security_updates_only: true
  update_schedule: "weekly"
  
  # Package lists
  essential_packages:
    - curl
    - vim
    - sudo
    - fail2ban
    - nftables
  
  security_packages:
    - aide
    - apparmor
    - apparmor-utils
    - apparmor-profiles
    - auditd
    - rkhunter
    - chkrootkit

# Logging Configuration
logging:
  # Centralized logging
  syslog_server: "{{ vault_syslog_server | default('') }}"
  log_retention_days: 90
  log_rotation: "daily"
  
  # Audit logging
  audit:
    enabled: true
    log_file: "/var/log/audit/audit.log"
    max_log_file_mb: 100
    num_logs: 5

# Monitoring Configuration
monitoring:
  # System monitoring
  system_metrics: true
  disk_usage_threshold: 85
  memory_usage_threshold: 90
  cpu_usage_threshold: 80
  
  # Alerting
  email_alerts: false
  email_recipients: []
  slack_webhook: "{{ vault_slack_webhook | default('') }}"

# Backup Configuration
backup:
  enabled: false
  backup_directory: "/var/backups"
  retention_days: 60
  compression: true
  encryption: false

# Development/Testing Configuration
development:
  # Test mode settings
  test_mode: false
  dry_run: false
  verbose_output: false
  
  # Debug settings
  debug_level: "info"
  log_ansible_tasks: false 